Crie um sistema capaz de resolver o problema das N-Rainhas através de busca
de melhoria iterativa (hill climbing ou têmpera simulada) para N com os seguintes
valores 10, 20 e 25. Tabele os tempos de processamento para obter uma solução.

In [107]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import colors
import re
import random

In [3]:
# #change file name
# path = "puzzle.sav"
# # -2: espaco vazio, -1: parede, 0 a 4: n de lampadas que podem iluminar, 5: lampada, 6: blocos iluminados 
# def load_puzzle(path):
#     file = open(path, "r")
#     desc = []
#     numered_block = {}
#     for line in file:
#         text = line.strip().split(":")
#         if text[0].strip() == "DESC":
#             desc = re.findall('.', text[2].strip())
#     grid = np.zeros((7, 7), dtype=int)
#     i = 0
#     run = 0
#     for x in range(7):
#         for y in range(7):
#             c = '\0'

#             if run == 0:
#                 c = desc[i]
#                 i = i + 1
#                 if c >= 'a' and c <= 'z':
#                     run = ord(c) - ord('a') + 1

#             if run > 0:
#                 c = 'S'
#                 run = run - 1

#             if c == '0' or c == '1' or c == '2' or c == '3' or c == '4':
#                 grid[x, y] = ord(c) - ord('0')
#                 numered_block[(x, y)] = grid[x, y]
#             elif c == 'B':
#                 grid[x, y] = -1
#             elif c == 'S':
#                 grid[x, y] = -2
#     return grid, numered_block

In [4]:
# path = 'puzzle.sav'
# # -2: espaco vazio, -1: parede, 0 a 4: n de lampadas que podem iluminar, 5: lampada, 6: blocos iluminados  
# grid, num_blocks = load_puzzle(path)
# print(grid)
# print(num_blocks)

In [30]:
grid = np.zeros((10, 10), dtype=int)
print(grid)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [155]:
# Modifica o grid com base no vetor de estados
# def set_state(state):

# Calcula o score do estado atual com base no número de rainhas que se atacam
# Score = Max - pares de raínhas que se atacam
def score_state(state):
    L = len(state)
    max_atacks = L*(L-1)/2
    state = np.insert(state, 0, 0, axis=0)
    score = 0
    for i in range(1, L+1):
        if i <= L:
            for j in range(i+1, L+1):
                if state[j] == state[i]:
                    score += 1
                elif abs(i - state[i]) == abs(j - state[j]):
                    score += 1
                elif state[i] + i == state[j] + j:
                    score += 1
    
    return max_atacks - score

def fitness_function(population):
    total_score = 0
    L = len(population)
    for person in population:
        total_score += score_state(person)
    
    if total_score == 0:
        return np.random.dirichlet(np.ones(L),size=1)
    
    result = np.array([])
    for i in range(L):
        result = np.insert(result, i, score_state(population[i])/total_score, axis=0)
    
    return result
    

In [138]:
a = np.array([])

In [139]:
a = np.insert(a, 0, 1, axis=0)

In [141]:
a[0]

1.0

In [159]:
population = np.array([[1, 3, 1, 1], [1, 2, 3, 4]])

In [150]:
len(population)

2

In [161]:
population[0]
score_state(population[1])

0.0

In [162]:
fitness_function(population)

array([1., 0.])

In [101]:
population[0]

[0, 0, 0, 1, 1, 1, 1]