Crie um sistema capaz de resolver o problema das N-Rainhas através de busca
de melhoria iterativa (hill climbing ou têmpera simulada) para N com os seguintes
valores 10, 20 e 25. Tabele os tempos de processamento para obter uma solução.

In [2]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import colors
import re
import random

In [3]:
# #change file name
# path = "puzzle.sav"
# # -2: espaco vazio, -1: parede, 0 a 4: n de lampadas que podem iluminar, 5: lampada, 6: blocos iluminados 
# def load_puzzle(path):
#     file = open(path, "r")
#     desc = []
#     numered_block = {}
#     for line in file:
#         text = line.strip().split(":")
#         if text[0].strip() == "DESC":
#             desc = re.findall('.', text[2].strip())
#     grid = np.zeros((7, 7), dtype=int)
#     i = 0
#     run = 0
#     for x in range(7):
#         for y in range(7):
#             c = '\0'

#             if run == 0:
#                 c = desc[i]
#                 i = i + 1
#                 if c >= 'a' and c <= 'z':
#                     run = ord(c) - ord('a') + 1

#             if run > 0:
#                 c = 'S'
#                 run = run - 1

#             if c == '0' or c == '1' or c == '2' or c == '3' or c == '4':
#                 grid[x, y] = ord(c) - ord('0')
#                 numered_block[(x, y)] = grid[x, y]
#             elif c == 'B':
#                 grid[x, y] = -1
#             elif c == 'S':
#                 grid[x, y] = -2
#     return grid, numered_block

In [4]:
# path = 'puzzle.sav'
# # -2: espaco vazio, -1: parede, 0 a 4: n de lampadas que podem iluminar, 5: lampada, 6: blocos iluminados  
# grid, num_blocks = load_puzzle(path)
# print(grid)
# print(num_blocks)

In [25]:
# Modifica o grid com base no vetor de estados
# def set_state(state):

# Calcula o score do estado atual com base no número de rainhas que se atacam
# Score = Número de pares de raínhas que se atacam
def score_state(state):
    L = len(state)
    max_atacks = L*(L-1)/2
    state.insert(0, 0) # Para indexar o vetor começando em 1
    score = 0
    for i in range(1, L+1):
        if i <= L:
            for j in range(i+1, L+1):
                if state[j] == state[i]:
                    score += 1
                elif abs(i - state[i]) == abs(j - state[j]):
                    score += 1
                elif state[i] + i == state[j] + j:
                    score += 1
    
    return max_atacks - score

In [6]:
grid = np.zeros((10, 10), dtype=int)
print(grid)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [7]:
# Vetor contendo a posição vertical das rainhas da esquerda para a direita. Primeira linha -> posic = 0
state = [1, 1, 1, 1]
# len(state)
score_state(state)

6

In [29]:
state = [1, 3, 1, 4]
score_state(state)

4.0